### PR TITLE
Fixed a few typos

### PR DESCRIPTION
**Pull request by WarpedWartWars**
Not all of them, though.

This isn't quite ready for pulling, because I need to fix all the typos first.

### CODE REVIEW

**Comment by jcubic** [comment]
Looks good. Will wait until you'll decide that it's ready. You can also use Grammarly online (if you don't use it) https://demo.grammarly.com/ where you can copy-paste the text and see if it doesn't suggest further improvements.

**Comment by WarpedWartWars** [comment]
I'm going to fix a few more typos.

**Comment by WarpedWartWars** [comment]
You can merge this now. I still have some typos left, though.

**Comment by jcubic** [comment]
There are lot more doc strings in lib directory in scheme files (*.scm).

**Comment by WarpedWartWars** [comment]
Ok. I'll take a look after I fix all the ones in `lips.js`.

**Comment by WarpedWartWars** [comment]
I made another commit, but I'm not actually sure if this pull request can be re-opened to merge it.

**Comment by jcubic** [comment]
I'm looking at old issues. If you still want to work on this or have some commit ready. Just open another PR with the same branch. Merged or closed PR can't be reopened.

**Comment by jcubic** [comment]
It seems that I've missed your message when it was first posted.

**Pull request merged**
