### PR TITLE
Fix possible typos and grammatical errors in the docstrings(the schematic files).

### PR DESCRIPTION
**Pull request by SachXD**
I've made quite a few changes in the files and yeah this is my 1st PR!

### CODE REVIEW

**Comment by jcubic** [comment]
Looks great, but you created the change on master branch. Can you make the changes on devel branch? I can't just change the target branch here, since I have some conflicts between master and devel.

You will need to reapply the changes on devel and see if there are no new functions in those files. There is a git command for moving single commits from branch to branch that maybe you can try, it's calling "cherry-pick".

**Comment by SachXD** [comment]
yeah, I'll try that!

**Comment by jcubic** [comment]
There are conficts, because devel branch is not in sync with master. That's why in CONTRIBUTOR.md file there is information to modify devel branch not master. Unfortunetlly I can't merge this PR as is.

**Comment by jcubic** [comment]
Another issues that automated tests only run on devel branch. So I don't know if your code doesn't break anything. The tests are there so I know that I don't make errors in code. Even if they are just typos in doc strings.

**Pull request closed without merging**
