### PR TITLE
typos/grammar in documentation

### PR DESCRIPTION
**Pull request by dragoncoder047**
I'm a native English speaker, so I guess I'm qualified to clean up the docstrings.

Largest changes: All occurrences of "Function return ...." were changed to "Returns ...." and likewise.

Also, I noticed that the documentation for the numerical comparison functions (`>` and friends) was at best confusing ("monotonically nondecreasing", wat?), and possibly completely backwards, so I rewrote it to what I think is correct, and added some explainer examples.

Feel free to reject any of my changes, especially if I misunderstood what the function does :)

### CODE REVIEW

**Comment by jcubic** [comment]
Thanks. There was an issue (#217) and some folks fixed some grammar mistakes during last year's Hacktoberfest but it seems not everything was fixed.

The build failed so the tests didn't even run, probably something with a branch name. I will try to fix it locally and you will merge it with devel.

**Comment by dragoncoder047** [comment]
I already did `make` (3bd529a8e65e05090a81132e0c38e4904284baf4) -- maybe that's why, there were no changes.

**Comment by jcubic** [comment]
CI/CD run `make`/`make lint`/`make test`.

What do you mean by no changes?

**Comment by dragoncoder047** [comment]
> What do you mean by no changes?

I had some github actions workflows on other repos of mine that run a build script and then git-commit the changes and push as the GHA bot. When I already built it myself in the previous commit, the git commit command failed with "no changes to commit" and exit status 1 which caused the action to say it failed.

**Comment by dragoncoder047** [comment]
Also, the last few lines of the action log that failed say:

```
sed -e "s/{{VER}}/1.0.0-beta.16/g" -e "s/{{BRANCH}}/`git branch | grep '^*' | sed 's/* //'`/g" -e "s/{{YEAR}}/`date +%Y`/g" \
-e "s/{{CHECKSUM}}/`cat tests/test.js tests/*.scm | md5sum | cut -d' ' -f 1`/g" -e "s/{{COMMIT}}/`git rev-parse HEAD`/g" -e "s/{{DATE}}/`date +%Y-%m-%d`/" \
-e "s/{{VER_DASH}}/`echo -n "1.0.0-beta.16" | sed "s/-/%E2%80%93/"`/g" < templates/README.md > README.md
sed: -e expression #2, char 40: unknown option to `s'
make: *** [Makefile:67: README.md] Error 1
Error: Process completed with exit code 2.
```
([direct link](https://github.com/jcubic/lips/actions/runs/6827289237/job/18571452484?pr=251#step:7:26))

**Comment by jcubic** [comment]
Please merge with [pr-build-fix](https://github.com/jcubic/lips/tree/pr-build-fix), I've fixed build and lint errors. Your lines were too long, the max is 90 characters.

**Comment by jcubic** [comment]
This project doesn't have any GitHub actions that do commits. There are only checks that make sure that the code builds and runs.

The problem was that Makefile by default on Ubuntu uses sh that point to dash. And on my system Fedora the sh point to bash.

**Comment by dragoncoder047** [comment]
OK, I merged pr-build-fix into my branch. (Did you mean to do the reverse -- set pr-build-fix as the PR target?)

**Comment by jcubic** [comment]
I don't understand why there are no my commits after merge.

**Comment by dragoncoder047** [comment]
Whoops, not sure why it didn't fetch all commits. Merged it all now.

**Comment by dragoncoder047** [comment]
sed is still borking it.

**Comment by jcubic** [comment]
Ok I solved the issue, the problem was that the branch in PR on GitHub have a slash. The branch name is `dragoncoder047/lips` and my sed command choked on slash when extracting the branch name and putting it into another sed command.

**Pull request merged**
